const palette = {
  emerald: "#1A7A5A",
  emeraldLight: "#2A9E74",
  emeraldDark: "#0F5940",
  amber: "#E8963A",
  amberLight: "#F5B060",
  amberDark: "#C57820",
  cream: "#FAF7F0",
  creamDark: "#F0EBE0",
  charcoal: "#1C2128",
  charcoalLight: "#2D3748",
  slate: "#4A5568",
  slateLight: "#718096",
  muted: "#A0ADB8",
  white: "#FFFFFF",
  offWhite: "#F7F9FC",
  red: "#E05252",
  green: "#27AE60",
  blue: "#3B82F6",
  purple: "#8B5CF6",
};

export default {
  light: {
    text: palette.charcoal,
    textSecondary: palette.slate,
    textMuted: palette.muted,
    muted: palette.muted,
    background: palette.cream,
    backgroundSecondary: palette.creamDark,
    backgroundCard: palette.white,
    tint: palette.emerald,
    tintLight: palette.emeraldLight,
    tintDark: palette.emeraldDark,
    accent: palette.amber,
    accentLight: palette.amberLight,
    accentDark: palette.amberDark,
    tabIconDefault: palette.muted,
    tabIconSelected: palette.emerald,
    border: "#E2E8F0",
    borderLight: "#EDF2F7",
    success: palette.green,
    error: palette.red,
    info: palette.blue,
    purple: palette.purple,
    shadow: "rgba(0,0,0,0.08)",
  },
};

export type ColorScheme = typeof import("./colors").default.light;
